#!/bin/sh
set -eu

dryad roots build --scope=dev --log-level="$DYD_LOG_LEVEL"

dryad run snapshot-test --scope=dev --log-level="$DYD_LOG_LEVEL"
dryad run smoke-test --scope=dev --log-level="$DYD_LOG_LEVEL"
