#!/usr/bin/env bash

#
# abort on error
# https://sipb.mit.edu/doc/safe-shell/
set -euf -o pipefail

_set_logging () {
    case $DYD_LOG_LEVEL in
        # turn on shell script debug logs for trace and debug log levels
        'debug' | 'trace' ) set -x ;;
        * ) ;;
    esac
}

_set_globals () {
    SRC_PACKAGE=$DYD_STEM
    SRC_ASSETS=$SRC_PACKAGE/dyd/assets

    # DEST_PACKAGE=$DYD_BUILD
    # DEST_ASSETS=$DEST_PACKAGE/dyd/assets
    # DEST_MAIN=$DEST_PACKAGE/dyd/commands/dyd-stem-run
    # DEST_TRAITS=$DEST_PACKAGE/dyd/traits

    PLATFORM="$DYD_OS-$DYD_ARCH"
}

_set_tests () {

    cd "$SRC_ASSETS"


    # find . -type f -name 'check.*.dhall' -print0 | sort -z | \
    #     xargs -0 -n1 -P$(nproc) \
    #     sh -c 'set -e; dhall --explain --file "$1" >/dev/null' _


    # run dhall normalization on all test check files to check
    # for assertion errors
    while IFS= read -r -d '' f; do
        echo "checking $f"
        time dhall --explain --file "$f" >/dev/null
        echo "done"
        echo ""
    done < <(find . -type f -name 'check.dhall' -print0 | sort -z)

}

_set_logging
_set_globals
_set_tests
