#!/usr/bin/env bash

#
# abort on error
# https://sipb.mit.edu/doc/safe-shell/
set -euf -o pipefail

_set_logging () {
    case $DYD_LOG_LEVEL in
        # turn on shell script debug logs for trace and debug log levels
        'debug' | 'trace' ) set -x ;;
        * ) ;;
    esac
}

_set_globals () {
    SRC_PACKAGE=$DYD_STEM
    SRC_ASSETS=$SRC_PACKAGE/dyd/assets

    # DEST_PACKAGE=$DYD_BUILD
    # DEST_ASSETS=$DEST_PACKAGE/dyd/assets
    # DEST_MAIN=$DEST_PACKAGE/dyd/commands/dyd-stem-run
    # DEST_TRAITS=$DEST_PACKAGE/dyd/traits

    PLATFORM="$DYD_OS-$DYD_ARCH"
}

_set_tests () {

    # echo "[info] formatting src"
    # z-format-src
    # echo "[info] done formatting src"

    # echo "[info] formatting tests"
    # # z-format-tests
    # echo "[info] done formatting tests"

    echo "[info] updating tests"

    cd "$SRC_ASSETS" && \
    find . -type f -name 'out.*.dhall' -print0 | sort -z | \
        xargs -0 -n1 -P$(nproc) \
        sh -c 'set -e; out="${1%.dhall}"; dhall text --file "$1" --output "$out"' _

    echo "[info] done updating tests"

    # while IFS= read -r -d '' f; do
    #     echo "cleaning $f"
    #     out="${f%.dhall}"   # strip the .dhall extension
    #     dhall text --file "$f" --output "$out"
    # done < <(find . -type f -name 'out.*.dhall' -print0 | sort -z)

}

_set_logging
_set_globals
_set_tests
