#!/usr/bin/env bash
set -euf -o pipefail

case "${DYD_LOG_LEVEL:-info}" in
  debug|trace) set -x ;;
  *) ;;
esac

cd "$DYD_STEM/dyd/assets"
"$DYD_STEM/dyd/dependencies/node/dyd/commands/npm" install --package-lock-only --ignore-scripts
